apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: developer-hub
type: Opaque
data:
  BACKEND_SECRET: <base64-encoded-value>
  K8S_SERVICE_ACCOUNT_TOKEN: <base64-encoded-value>
  POSTGRES_PASSWORD: <base64-encoded-value>
  POSTGRES_USER: <base64-encoded-value>
  OAUTH2_PROXY_AUTH_URL: <base64-encoded-value>
  OAUTH2_PROXY_CLIENT_ID: <base64-encoded-value>
  OAUTH2_PROXY_CLIENT_SECRET: <base64-encoded-value>
  OAUTH2_PROXY_TOKEN_URL: <base64-encoded-value>
