apiVersion: v1
kind: Secret
metadata:
  name: backstage-servicenow-secret
  namespace: developer-hub
type: Opaque
data:
  SERVICENOW_BASE_URL: <base64-encoded-value>
  SERVICENOW_USERNAME: <base64-encoded-value>
  SERVICENOW_PASSWORD: <base64-encoded-value>
  SN_BASE_URL: <base64-encoded-value>
  SN_USER: <base64-encoded-value>
  SN_PASSWORD: <base64-encoded-value>
  SN_BASIC_AUTH: <base64-encoded-value>
